version: '3'

tasks:
  delete:
    desc: Delete Longhorn
    cmds:
      - 'kubectl -n longhorn-system patch -p ''{"value": "true"}'' --type=merge lhs deleting-confirmation-flag'
      - helm uninstall longhorn -n longhorn-system
      - kubectl delete -f https://raw.githubusercontent.com/longhorn/longhorn/v1.6.1/deploy/longhorn.yaml
