version: "3"

includes:
  longhorn:
    taskfile: ../longhorn/Taskfile.yml
    internal: true

tasks:
  apply:
    desc: Apply helmfile releases
    cmds:
      - helmfile -f {{.HELMFILE_PATH}} apply

  destroy:
    desc: Destroy helmfile releases
    cmds:
      - |
        if kubectl get namespace longhorn-system &> /dev/null; then
          task longhorn:delete
        fi
      - helmfile -f {{.HELMFILE_PATH}} destroy

  lint:
    desc: Lint helmfile releases
    cmds:
      - helmfile -f {{.HELMFILE_PATH}} lint

  sync:
    desc: Sync all helmfile resources
    cmds:
      - helmfile -f {{.HELMFILE_PATH}} sync

  reset:
    desc: Destroy and apply helmfile releases
    cmds:
      - task: destroy
      - task: apply
