version: "3"
includes:
  markdown:
    taskfile: ./markdown/Taskfile.yml
    aliases:
      - md
  yaml:
    taskfile: ./yaml/Taskfile.yml

tasks:
  default:
    desc: default task
    cmds:
      - task --list

  lint:
    desc: Lint README
    cmds:
      - task: md:lint

  fmt:
    desc: Format files
    cmds:
      - task: yaml:format
