version: '3'

includes:
  markdown:
    taskfile: ./markdown/Taskfile.yml
    aliases:
      - md
    vars:
      MARKDOWN_FILES: README.md

tasks:
  default:
    desc: default task
    cmds:
      - task --list

  lint:
    desc: Lint README
    cmds:
      - task: md:lint
