version: "3"

tasks:
  lint:
    desc: Lint markdown files
    preconditions:
      - sh: which npx
        msg: "npx is not installed. Please install Node.js from https://nodejs.org/"
    cmds:
      - npx -y markdownlint-cli2 --fix {{.MARKDOWN_FILES}}
    requires:
      vars: [MARKDOWN_FILES]

  format:
    desc: Format markdown files
    preconditions:
      - sh: which npx
        msg: "npx is not installed. Please install Node.js from https://nodejs.org/"
    cmds:
      - npx --yes doctoc --github {{.MARKDOWN_FILES}}
    requires:
      vars: [MARKDOWN_FILES]
