version: "3"

tasks:
  install-linux:
    desc: Install minikube on linux
    summary: Installs minikube as described in https://minikube.sigs.k8s.io/docs/start/
    internal: true
    requires:
      vars:
        # List of supported architectures found in https://minikube.sigs.k8s.io/docs/start/
        - ARCH
    cmds:
      - cmd: curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-{{.ARCH}}
      - cmd: sudo install minikube-linux-{{.ARCH}} /usr/local/bin/minikube && rm minikube-linux-{{.ARCH}}
    status:
      - test -f /usr/local/bin/minikube

  install-darwin-arm64:
    desc: Install minikube on Apple Silicon
    summary: Installs minikube as described in https://minikube.sigs.k8s.io/docs/start/
    internal: true
    cmds:
      - cmd: curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-darwin-arm64
      - cmd: sudo install minikube-darwin-arm64 /usr/local/bin/minikube

  load-images:
    desc: Load local images into minikube to speed up start time
    cmds:
      - for: { var: IMAGES }
        cmd: minikube image load {{.ITEM}}

  restart:
    desc: Delete and start cluster
    cmds:
      - minikube delete && minikube start
